name: Cron Job to scrape rooms pricing

on:
  workflow_dispatch:
  # Uncomment following lines to run Daily Cron Job
  schedule:
    # Run everyday at 08:00 AM every day
    - cron: "0 8 * * *"

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install Script Requirements
        run: pip3 install -r requirements.txt

      - name: Run python script
        env:
          NTFY_TOPIC: ${{secrets.NTFY_TOPIC}}
          BASE_URL: ${{vars.ROOMS_SCRIPT_BASE_URL}}
          PROXY_URL: ${{vars.PROXY_URL}}
          PROXY_USER: ${{vars.PROXY_USER}}
          PROXY_PASSWORD: ${{secrets.PROXY_PASSWORD}}

        run: python3 rooms-scrapping.py
